version: "3.9"

services:
  as:
    build: ./as
    container_name: as
    ports:
      - "53533:53533/udp"
    volumes:
      - ./AS:/AS
    networks:
      - fibnet

  fs:
    build: ./fs
    container_name: fs
    ports:
      - "9090:9090"
    networks:
      - fibnet
    depends_on:
      - as

  us:
    build: ./us
    container_name: us
    ports:
      - "8080:8080"
    networks:
      - fibnet
    depends_on:
      - fs
      - as

networks:
  fibnet:
    driver: bridge
